# Generated by Django 4.0.6 on 2023-01-29 06:45

from django.db import migrations, models
import problems.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reportDateTime', models.DateTimeField()),
                ('multipleAffectedUser', models.BooleanField()),
                ('affectedUserSize', models.IntegerField()),
                ('ticketDateTime', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('ticketNumber', models.IntegerField(default=problems.models.Problem.ids, unique=True)),
                ('isAssigned', models.BooleanField(default=False)),
            ],
        ),
    ]
