# Generated by Django 4.0.6 on 2023-01-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('priority', '0001_initial'),
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='assignedTechId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemAssignedTech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemimpact_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='problem',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problempriority_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='problem',
            name='security_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemSecGroup', to='users.securitygroup'),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priority.status', to_field='status_id'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ticketOwnerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemTicketOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='ticketOwnerSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemSection', to='users.course'),
        ),
        migrations.AddField(
            model_name='problem',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemurgency_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='problem',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userProblemId', to=settings.AUTH_USER_MODEL),
        ),
    ]
