# Generated by Django 4.0.6 on 2023-01-29 06:45

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('asset_dependencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['0'], size=None)),
                ('location', models.CharField(max_length=100)),
                ('asset_resources', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_status_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('current_version', models.CharField(max_length=100)),
                ('license_name', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=100)),
                ('vendor_support', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('license_cost', models.IntegerField()),
            ],
        ),
    ]
