# Generated by Django 4.0.6 on 2023-03-05 14:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_status_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('current_version', models.CharField(max_length=100)),
                ('license_name', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=100)),
                ('vendor_support', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('license_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('asset_dependencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['0'], size=None)),
                ('location', models.CharField(max_length=100)),
                ('asset_resources', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedUserId', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetCourse', to='users.course')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdById', to=settings.AUTH_USER_MODEL)),
                ('license_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenseId', to='assets.license')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset_status', to_field='asset_status_id')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userAssetId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
