# Generated by Django 4.0.6 on 2023-01-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changes', '0001_initial'),
        ('priority', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='assignedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedToId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='backout_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backoutplan', to='changes.backoutplan'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='business_justification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessjustificationId', to='changes.businessjustification'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='communication_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communicationPlan', to='changes.communicationplan'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeimpact_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='install_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installplan', to='changes.installplan'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='ownerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changepriority_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requestOwnerSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseId', to='users.course'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requestedById',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestedId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='risk_assesment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riskAssesment', to='changes.riskassesment'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeurgency_id', to='priority.priority', to_field='priority_id'),
        ),
    ]
