# Generated by Django 4.0.6 on 2023-01-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
        ('priority', '0001_initial'),
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignedTechId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedIncidentTech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentimpact_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentpriority_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='incident',
            name='problemsRelated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedItems', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='incident',
            name='security_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secGroup', to='users.securitygroup'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priority.status', to_field='status_id'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticketOwnerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncidentTicketOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticketOwnerRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncidentTicketrole', to='users.role', to_field='roleId'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticketOwnerSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentTicketCourse', to='users.course'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticketType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentTicketType', to='incidents.tickettype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidenturgency_id', to='priority.priority', to_field='priority_id'),
        ),
        migrations.AddField(
            model_name='incident',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userincidentId', to=settings.AUTH_USER_MODEL),
        ),
    ]
